[package]
name = "leptos-md-editor"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
js-sys = "0.3.77"
leptos = "0.7.8"
reqwest = { version = "0.12.15" , features = ["json"] }
serde_json = "1.0.140"
wasm-bindgen = "0.2.100"
wasm-bindgen-futures = "0.4.50"
web-sys = "0.3.77"

